version: '3.3'
services:

        nginx:
                container_name: door2door-nginx
                restart: always
                volumes:
                        - './nginx/html:/var/www/door2door.dk/html:ro'
                        - '/etc/letsencrypt/live/door2door.dk/fullchain.pem:/etc/ssl/certs/fullchain.pem'
                        - '/etc/letsencrypt/live/door2door.dk/privkey.pem:/etc/ssl/certs/privkey.pem'
                        - './nginx/logs:/var/log/nginx'
                        - './nginx/nginx.conf:/etc/nginx/nginx.conf'
                        - './nginx/sites-enabled:/etc/nginx/sites-enabled/'
                ports:
                        - '80:80'
                        - '443:443'
                image: nginx

        mssql:
                container_name: door2door-mssql
                restart: always
                hostname: door2door-mssql
                environment:
                        - ACCEPT_EULA=Y
                        - SA_PASSWORD=F5%ajdoiwjdiwojdoiw
                volumes:
                        - './mssql/data:/var/opt/mssql/data'
                        - './mssql/log:/var/opt/mssql/log'
                        - './mssql/secrets:/var/opt/mssql/secrets'
                ports:
                        - '1433:1433'
                expose:
                        - "6379"
                networks:
                        - backend
                image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
        api:
                container_name: door2door-api
                restart: always
                ports:
                        - '5000:80'
                        - '5001:443'
                volumes:
                        - '/etc/letsencrypt/live/door2door.dk:/https:ro'
                depends_on:
                        - mssql
                environment:
                        - SQL_CONNECTION_STRING=Data Source=mssql;Initial Catalog=Door2doorZbc;User ID=sa;Password=F5%ajdoiwjdiwojdoiw
                        - 'ASPNETCORE_URLS=https://+;http://+'
                        - ASPNETCORE_HTTPS_PORT=5001
                        - ASPNETCORE_Kestrel__Certificates__Default__Password=DJwd382u8d/2ej9d2j3J
                        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Cert.pfx
                networks:
                        - backend
                image: door2door_api

networks:
        backend:
                driver: bridge
