version: '3.3'
services:
    nginx:
        container_name: door2door-nginx
        restart: always
        volumes:
            - './nginx/html:/var/www/door2door.dk/html:ro'
            - '/etc/letsencrypt/live/door2door.dk/fullchain.pem:/etc/ssl/certs/fullchain.pem'
            - '/etc/letsencrypt/live/door2door.dk/privkey.pem:/etc/ssl/certs/privkey.pem'
            - './nginx/logs:/var/log/nginx'
            - './nginx/nginx.conf:/etc/nginx/nginx.conf'
            - './nginx/sites-enabled:/etc/nginx/sites-enabled/'
        ports:
            - '80:80'
            - '443:443'
        image: nginx

